### ISSUE TITLE
Errors when running the bot

### ISSUE THREAD

**Issue by Deputy1389** [darkmatter2222/EVE-Online-Bot#13]
The range_grid_search_assets_box is not shown on your example setup and Im not sure what its for

![image](https://github.com/darkmatter2222/EVE-Online-Bot/assets/15461586/d0939286-5ecf-4bc9-90b3-5169f3014ec3)

And after I set up the boxes Im not really sure how Im supposed to exit the setup so I just close the command prompt and try to run the bot but I get an error

`(myenv) D:\Games\eve\EVE-Online-Bot-main>Start_AI_Pilot.py --config_file "AI_Pilot\ai_pilot_config_v2.json" --headless_miner 1
2023-07-05 07:57:32.267 | INFO     | __main__:<module>:11 - Adding: D:\Games\eve\EVE-Online-Bot-main\Start_AI_Pilot.py to path
2023-07-05 07:57:32.268 | INFO     | __main__:<module>:14 - ['D:\\Games\\eve\\EVE-Online-Bot-main', 'D:\\python\\python39.zip', 'D:\\python\\DLLs', 'D:\\python\\lib', 'D:\\python', 'D:\\Games\\eve\\EVE-Online-Bot-main\\myenv', 'D:\\Games\\eve\\EVE-Online-Bot-main\\myenv\\lib\\site-packages', 'D:\\Games\\eve\\EVE-Online-Bot-main\\myenv\\lib\\site-packages\\win32', 'D:\\Games\\eve\\EVE-Online-Bot-main\\myenv\\lib\\site-packages\\win32\\lib', 'D:\\Games\\eve\\EVE-Online-Bot-main\\myenv\\lib\\site-packages\\Pythonwin', 'D:\\Games\\eve\\EVE-Online-Bot-main']
Traceback (most recent call last):
  File "D:\Games\eve\EVE-Online-Bot-main\Start_AI_Pilot.py", line 53, in <module>
    start_mining(params.config_file)
  File "D:\Games\eve\EVE-Online-Bot-main\AI_Pilot\Objectives\Mining\StartMining.py", line 26, in start_mining
    Bot = Bot_Engine(config_dir=config_dir)
  File "D:\Games\eve\EVE-Online-Bot-main\AI_Pilot\Bot_Engine\Bot_Engine.py", line 54, in __init__
    self.ag.up = universal_predictor(config=self.ag.ml_botting_core_config)
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\base.py", line 33, in __init__
    self.load_models()
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\base.py", line 38, in load_models
    self.classifiers = load_models_from_config(self.config)
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\model_management\model_manager.py", line 48, in load_models_from_config
    process_model_config(config)
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\model_management\model_manager.py", line 35, in process_model_config
    construct_dirs(config_record)
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\model_management\model_manager.py", line 14, in construct_dirs
    mkdir_p(config_record['model_root_directory'])
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\ml_botting_core\general\general.py", line 6, in mkdir_p
    os.makedirs(path)
  File "D:\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'O:\\'`

**Comment by darkmatter2222** [comment]
Hello @Deputy1389,

This project is far from a finished polished product. Some python skills and ability to interoperate and configure the bot are required at this time. 

You did the right thing by closing the CLI when finished adjusting the ranges, each time you move a rage and lift the mouse, it updates the config file.

The error you are getting describes how the 'O://' Directory is not found on your PC.  Understandable, on my PC i have many drive letters.

Simply update your configurations to a directory more appropriate for your PC.
Look through the config file here:
https://github.com/darkmatter2222/EVE-Online-Bot/blob/main/AI_Pilot/ai_pilot_config_v2.json and update the directories with directory locations suitable for your PC.  Simply changing to d: in your case will likely fix.

**Comment by Deputy1389** [comment]
Okay, so I got that figured out. Thanks

But I'm not sure what to set the log_dir to

`Traceback (most recent call last):
  File "D:\Games\eve\EVE-Online-Bot-main\Start_AI_Pilot.py", line 61, in <module>
    start_mining(params.config_file)
  File "D:\Games\eve\EVE-Online-Bot-main\AI_Pilot\Objectives\Mining\StartMining.py", line 29, in start_mining
    logger.add(Bot.ag.this_config['general']['log_dir'] + '\\' + host + "Audit_History{time}.log")
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\loguru\_logger.py", line 762, in add
    wrapped_sink = FileSink(path, **kwargs)
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\loguru\_file_sink.py", line 166, in __init__
    self._initialize_file()
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\loguru\_file_sink.py", line 185, in _initialize_file
    path = self._prepare_new_path()
  File "D:\Games\eve\EVE-Online-Bot-main\myenv\lib\site-packages\loguru\_file_sink.py", line 181, in _prepare_new_path
    os.makedirs(dirname, exist_ok=True)
  File "D:\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 53] The network path was not found: '\\\\databrick\\N\\'`

**Comment by darkmatter2222** [comment]
@Deputy1389, same at the "O:/" error.  

In that same config file, please "\\\\databrick\\N\\" with a more suitable Log directory such as "D:/"
