### ISSUE TITLE
Mining Bot did not launch the game

### ISSUE THREAD

**Issue by fullstar5** [darkmatter2222/EVE-Online-Bot#16]
Hi! Thank you for posting this repo, it looks absolute fantastic!

I was testing auto mining bot. Everything was running smoothly until it stucked on launch page, it didn't click 'PLAY NOW' button and fall into infiinte waiting-sleeping loop. The error shows like this (on cmd):

2024-01-14 03:27:11.023 | DEBUG    | ml_botting_core.base:__init__:34 - universal_predictor initialized
2024-01-14 03:27:11.028 | INFO     | AI_Pilot.Game_Functions.Game_Client.Game_Client:login_sequience:10 - Beginning Login Sequence...
2024-01-14 03:27:11.029 | INFO     | AI_Pilot.Game_Functions.Game_Client.Game_Client:login_sequience:11 - Starting Launcher...
2024-01-14 03:27:19.708 | INFO     | AI_Pilot.Game_Functions.Game_Client.Game_Client:start_launcher:78 - starting launcher, waiting 30 seconds...
2024-01-14 03:27:57.387 | INFO     | AI_Pilot.Objectives.Mining.StartMining:start_mining:73 - Main Loop-Exception:Eve Launcher Did Not Start
2024-01-14 03:27:57.387 | ERROR    | AI_Pilot.Objectives.Mining.StartMining:start_mining:74 - Eve Launcher Did Not Start
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\EVE-Online-Bot-main\Start_AI_Pilot.py", line 61, in <module>
    start_mining(params.config_file)
    │            │      └ 'AI_Pilot\\ai_pilot_config_v2.json'
    │            └ Namespace(config_file='AI_Pilot\\ai_pilot_config_v2.json', headless_miner=True, headless_project_discovery=False, setup_mode=...
    └ <function start_mining at 0x0000019339959940>

> File "C:\Users\Administrator\Desktop\EVE-Online-Bot-main\AI_Pilot\Objectives\Mining\StartMining.py", line 38, in start_mining
    launcher_pid, game_pid = login_sequience(Bot.ag)
    │                        │               │   └ <AI_Pilot.Bot_Engine.Bot_Engine.active_globals object at 0x000001933995F820>
    │                        │               └ <AI_Pilot.Bot_Engine.Bot_Engine.Bot_Engine object at 0x000001933995F8E0>
    │                        └ <function login_sequience at 0x0000019339959670>
    └ None

  File "C:\Users\Administrator\Desktop\EVE-Online-Bot-main\AI_Pilot\Game_Functions\Game_Client\Game_Client.py", line 12, in login_sequience
    launcher_pid = start_launcher(ag)
                   │              └ <AI_Pilot.Bot_Engine.Bot_Engine.active_globals object at 0x000001933995F820>
                   └ <function start_launcher at 0x0000019339959790>

  File "C:\Users\Administrator\Desktop\EVE-Online-Bot-main\AI_Pilot\Game_Functions\Game_Client\Game_Client.py", line 88, in start_launcher
    raise Exception("Eve Launcher Did Not Start")

Exception: Eve Launcher Did Not Start
2024-01-14 03:30:37.728 | INFO     | AI_Pilot.Objectives.Mining.StartMining:start_mining:78 - Main Loop-Sleeping 30 seconds...

I'm running on python 3.9.13 and win10. I can't find 'Launcher' folder and 'evelauncher.exe' file mentioned in config file so I put "C:\\Users\\Administrator\\AppData\\Local\\eve-online\\eve-online.exe" under as launcher route.
btw project discovery bot works fine.

**Comment by eskaroo** [comment]
Same issue cant start game with mining bot (tried all eve exe files).
